export { default as Navbar } from "./Navbar"
export { default as Footer } from "./Footer" 
export { default as Hero } from "./Hero"
export { default as AboutMe } from "./AboutMe"
export { default as ContactMe } from "./ContactMe"
export { default as Project } from "./Project"
export { default as GetInTouch } from "./GetInTouch"
export { default as ContactInfo } from "./ContactInfo"